services:
  db:
    image: postgres:14.1-alpine
    restart: always
    command: ["postgres", "-c", "log_statement=all"]
    environment:
      - CHOKIDAR_USEPOLLING=true
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5432:5432'
    volumes:
      - ./backend/db:/var/lib/postgresql/data
    networks:
      - api-db
  backend:
    build: backend
    ports:
      - 8080:8080
    volumes:
      - ./backend:/app
    networks:
      - ui-api
      - api-db
  frontend:
    build: frontend
    ports:
      - 80:3000
    volumes:
      - ./frontend:/app
    networks:
      - ui-api
networks:
  ui-api:
  api-db:
volumes:
  backend:
    driver: local
  frontend:
    driver: local
  db:
    driver: local