services:
  db:
    image: postgres:14.1-alpine
    restart: always
    command: ["postgres", "-c", "log_statement=all"]
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: quickstream
      POSTGRES_HOST_AUTH_METHOD: password
    ports:
      - '5432:5432'
    volumes:
      - ./backend/data/db:/var/lib/postgresql/data
    networks:
      - api-db
  backend:
    build: backend
    ports:
      - 8080:8080
    environment:
      - VIDEOS_PATH=/app/data/videos/
    volumes:
      - ./backend:/app
      - ./backend/data/videos:/app/data/videos/
    networks:
      - ui-api
      - api-db
  frontend:
    build: ./frontend
    environment:
      WDS_SOCKET_PORT: 80
    ports:
      - 80:3000
    volumes:
      - ./frontend:/app
    networks:
      - ui-api
networks:
  ui-api:
  api-db:
volumes:
  backend:
    driver: local
  frontend:
    driver: local
  db:
    driver: local