services:
  backend:
    build: backend
    ports:
      - 8080:8080
    volumes:
      - ./backend:/app
    networks:
      - spring-postgres
  frontend:
    build: frontend
    ports:
      - 80:3000
    volumes:
      - ./frontend:/app
    networks:
      - spring-postgres
networks:
  spring-postgres: